name: Test

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Icarus Verilog
      run: |
        sudo apt-get install -y --no-install-recommends iverilog

    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt

    - name: Test with Cocotb
      run: make
