name: Test

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Icarus Verilog Dependencies
      run: |
        sudo apt-get install -y --no-install-recommends gperf flex g++
    
    - name: Cache Icarus Verilog Build
      uses: actions/cache@v3
      with:
        path: verilog_build
        key: ${{ runner.os }}-3

    - name: Prepare Icarus Verilog source
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        wget "https://github.com/steveicarus/iverilog/archive/refs/tags/v11_0.tar.gz"
        mkdir verilog_build
        tar zxf v11_0.tar.gz --strip-components=1 -C verilog_build
        cd verilog_build && sh autoconf.sh && ./configure

    - name: Build and Install Icarus Verilog
      working-directory: verilog_build
      run: |
        make
        sudo make install

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements.txt

    - name: Test with Cocotb
      run: make test
